# fly.toml app configuration file generated for store-lcd-1 on 2023-12-28T11:48:59+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "store-lcd-1"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[env]
  PORT = "8081"
  SHOPIFY_APP_URL = "https://store-lcd-1.fly.dev"
  SCOPES = "read_orders, read_products"

