# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "The Display"
client_id = "3a6140b1c0f2e9ff71553fd240681e7e"
application_url = "https://store-lcd-1.fly.dev"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products"

[auth]
redirect_urls = [
  "https://store-lcd-1.fly.dev/auth/callback",
  "https://store-lcd-1.fly.dev/auth/shopify/callback",
  "https://store-lcd-1.fly.dev/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
dev_store_url = "stats-display.myshopify.com"

