// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void init_app(lv_event_t * e);
void save_settings_screen(lv_event_t * e);
void screen_brightness_slider(lv_event_t * e);
void WifiKeyboardReady(lv_event_t * e);
void wifi_scan_button_cb(lv_event_t * e);
void software_upgrade_button(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
